--
-- PostgreSQL database dump
--

-- Dumped from database version 14.15
-- Dumped by pg_dump version 14.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: databasechangelog; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


--
-- Name: databasechangeloglock; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


--
-- Name: dependencies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dependencies (
    id bigint NOT NULL,
    type text NOT NULL,
    name text NOT NULL,
    version text NOT NULL,
    version_num bigint
);


--
-- Name: dependencies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dependencies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dependencies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: deployments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.deployments (
    id bigint NOT NULL,
    name text NOT NULL,
    version text NOT NULL,
    environment text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: deployments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.deployments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deployments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: entities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.entities (
    id bigint NOT NULL,
    name text NOT NULL,
    version text NOT NULL,
    stage text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: entities_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.entities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.entities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: entity_dependencies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.entity_dependencies (
    entity_id bigint NOT NULL,
    dependency_id bigint NOT NULL
);


--
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- Name: dependencies dependencies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dependencies
    ADD CONSTRAINT dependencies_pkey PRIMARY KEY (id);


--
-- Name: dependencies dependencies_type_name_version_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dependencies
    ADD CONSTRAINT dependencies_type_name_version_uniq UNIQUE (type, name, version);


--
-- Name: deployments deployments_name_version_environment_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deployments
    ADD CONSTRAINT deployments_name_version_environment_uniq UNIQUE (name, version, environment);


--
-- Name: deployments deployments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deployments
    ADD CONSTRAINT deployments_pkey PRIMARY KEY (id);


--
-- Name: entities entities_name_version_stage_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entities
    ADD CONSTRAINT entities_name_version_stage_uniq UNIQUE (name, version, stage);


--
-- Name: entities entities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entities
    ADD CONSTRAINT entities_pkey PRIMARY KEY (id);


--
-- Name: entity_dependencies entity_dependencies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entity_dependencies
    ADD CONSTRAINT entity_dependencies_pkey PRIMARY KEY (entity_id, dependency_id);


--
-- Name: idx_dependencies_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dependencies_name ON public.dependencies USING btree (name);


--
-- Name: idx_dependencies_name_version_num; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dependencies_name_version_num ON public.dependencies USING btree (name, type, version_num);


--
-- Name: idx_deployment_environment_name_version; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_deployment_environment_name_version ON public.deployments USING btree (environment, name, version);


--
-- Name: idx_entities_name_version_stage; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_entities_name_version_stage ON public.entities USING btree (name, version, stage);


--
-- Name: idx_entity_dependencies_dependency; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_entity_dependencies_dependency ON public.entity_dependencies USING btree (dependency_id);


--
-- Name: idx_entity_dependencies_entity; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_entity_dependencies_entity ON public.entity_dependencies USING btree (entity_id);


--
-- Name: entity_dependencies entity_dependencies_dependency_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entity_dependencies
    ADD CONSTRAINT entity_dependencies_dependency_fk FOREIGN KEY (dependency_id) REFERENCES public.dependencies(id) ON DELETE CASCADE;


--
-- Name: entity_dependencies entity_dependencies_entity_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entity_dependencies
    ADD CONSTRAINT entity_dependencies_entity_fk FOREIGN KEY (entity_id) REFERENCES public.entities(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

