SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
SET default_table_access_method = heap;
SET search_path = 'public';

create table if not exists entities
(
  id         bigint generated by default as identity
    primary key,
  name       text                                   not null,
  version    text                                   not null,
  stage      text                                   not null,
  created_at timestamp with time zone default now() not null,
  constraint entities_name_version_stage_uniq
    unique (name, version, stage)
);

create index if not exists idx_entities_name_version_stage
  on entities (name, version, stage);

create table if not exists dependencies
(
  id          bigint generated by default as identity
    primary key,
  type        text not null,
  name        text not null,
  version     text not null,
  version_num bigint,
  constraint dependencies_type_name_version_uniq
    unique (type, name, version)
);

create index if not exists idx_dependencies_name_version_num
  on dependencies (name, type, version_num);

create index if not exists idx_dependencies_name
  on dependencies (name);

create table if not exists entity_dependencies
(
  entity_id     bigint not null,
  dependency_id bigint not null,
  primary key (entity_id, dependency_id)
);

create index if not exists idx_entity_dependencies_entity
  on entity_dependencies (entity_id);

create index if not exists idx_entity_dependencies_dependency
  on entity_dependencies (dependency_id);

create table if not exists deployments
(
  id          bigint generated by default as identity
    primary key,
  name        text                                   not null,
  version     text                                   not null,
  environment text                                   not null,
  updated_at  timestamp with time zone default now() not null,
  constraint deployments_name_version_environment_uniq
    unique (name, version, environment)
);

create index if not exists idx_deployment_environment_name_version
  on deployments (environment, name, version);

create table if not exists tags
(
  entity_name    text not null,
  entity_version text not null,
  value          text not null,
  constraint pk_tags
    primary key (entity_name, entity_version, value),
  constraint tag_unique_by_name_value
    unique (entity_name, value)
);

create index if not exists idx_tag_value
  on tags (value);

create table if not exists labels
(
  entity_name text not null,
  key         text not null,
  value       text not null,
  constraint pk_labels
    primary key (entity_name, key, value)
);
